const std = @import("std");
const cli = @import("cli.zig");
const fs = std.fs;

const readme_template =
    \\# {project_name}
    \\
    \\{description}
    \\
    \\## Installation
    \\
    \\```bash
    \\# Add installation instructions here
    \\```
    \\
    \\## Usage
    \\
    \\```bash
    \\# Add usage examples here
    \\```
    \\
    \\## Features
    \\
    \\- Feature 1
    \\- Feature 2
    \\- Feature 3
    \\
    \\## Contributing
    \\
    \\Contributions are welcome! Please feel free to submit a Pull Request.
    \\
    \\## License
    \\
    \\This project is licensed under the MIT License - see the LICENSE file for details.
    \\
;

const mit_license_template =
    \\MIT License
    \\
    \\Copyright (c) {year} {author}
    \\
    \\Permission is hereby granted, free of charge, to any person obtaining a copy
    \\of this software and associated documentation files (the "Software"), to deal
    \\in the Software without restriction, including without limitation the rights
    \\to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    \\copies of the Software, and to permit persons to whom the Software is
    \\furnished to do so, subject to the following conditions:
    \\
    \\The above copyright notice and this permission notice shall be included in all
    \\copies or substantial portions of the Software.
    \\
    \\THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    \\IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    \\FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    \\AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    \\LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    \\OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    \\SOFTWARE.
;

const apache2_license_template =
    \\Copyright {year} {author}
    \\
    \\Licensed under the Apache License, Version 2.0 (the "License");
    \\you may not use this file except in compliance with the License.
    \\You may obtain a copy of the License at
    \\
    \\    http://www.apache.org/licenses/LICENSE-2.0
    \\
    \\Unless required by applicable law or agreed to in writing, software
    \\distributed under the License is distributed on an "AS IS" BASIS,
    \\WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    \\See the License for the specific language governing permissions and
    \\limitations under the License.
;

const gpl3_license_header =
    \\{project_name}
    \\Copyright (C) {year} {author}
    \\
    \\This program is free software: you can redistribute it and/or modify
    \\it under the terms of the GNU General Public License as published by
    \\the Free Software Foundation, either version 3 of the License, or
    \\(at your option) any later version.
    \\
    \\This program is distributed in the hope that it will be useful,
    \\but WITHOUT ANY WARRANTY; without even the implied warranty of
    \\MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    \\GNU General Public License for more details.
    \\
    \\You should have received a copy of the GNU General Public License
    \\along with this program.  If not, see <https://www.gnu.org/licenses/>.
;

const gitignore_node =
    \\# Dependencies
    \\node_modules/
    \\/bower_components/
    \\
    \\# Production
    \\/build
    \\/dist
    \\
    \\# Generated files
    \\.docusaurus
    \\.cache-loader
    \\
    \\# Misc
    \\.DS_Store
    \\.env.local
    \\.env.development.local
    \\.env.test.local
    \\.env.production.local
    \\
    \\npm-debug.log*
    \\yarn-debug.log*
    \\yarn-error.log*
;

const gitignore_python =
    \\# Byte-compiled / optimized / DLL files
    \\__pycache__/
    \\*.py[cod]
    \\*$py.class
    \\
    \\# Virtual environments
    \\venv/
    \\env/
    \\ENV/
    \\.venv
    \\
    \\# Distribution / packaging
    \\.Python
    \\build/
    \\develop-eggs/
    \\dist/
    \\*.egg-info/
    \\
    \\# Unit test / coverage reports
    \\.coverage
    \\.pytest_cache/
    \\
    \\# Jupyter Notebook
    \\.ipynb_checkpoints
    \\
    \\# pyenv
    \\.python-version
;

const gitignore_zig =
    \\# Zig build artifacts
    \\zig-cache/
    \\zig-out/
    \\
    \\# Test artifacts
    \\*.test
    \\
    \\# Editor directories
    \\.vscode/
    \\.idea/
;

const gitignore_rust =
    \\# Generated by Cargo
    \\/target/
    \\
    \\# Cargo lock file
    \\Cargo.lock
    \\
    \\# These are backup files generated by rustfmt
    \\**/*.rs.bk
    \\
    \\# MSVC Windows builds
    \\*.pdb
;

const gitignore_go =
    \\# Binaries for programs and plugins
    \\*.exe
    \\*.exe~
    \\*.dll
    \\*.so
    \\*.dylib
    \\
    \\# Test binary, built with `go test -c`
    \\*.test
    \\
    \\# Output of the go coverage tool
    \\*.out
    \\
    \\# Dependency directories
    \\vendor/
    \\
    \\# Go workspace file
    \\go.work
;

const gitignore_general =
    \\# OS generated files
    \\.DS_Store
    \\.DS_Store?
    \\._*
    \\.Spotlight-V100
    \\.Trashes
    \\ehthumbs.db
    \\Thumbs.db
    \\
    \\# Editor directories and files
    \\.idea/
    \\.vscode/
    \\*.swp
    \\*.swo
    \\*~
    \\
    \\# Logs
    \\logs/
    \\*.log
    \\
    \\# Environment variables
    \\.env
    \\.env.local
;

const changelog_template =
    \\# Changelog
    \\
    \\All notable changes to this project will be documented in this file.
    \\
    \\The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
    \\and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
    \\
    \\## [Unreleased]
    \\
    \\### Added
    \\- Initial project setup
    \\
    \\### Changed
    \\
    \\### Deprecated
    \\
    \\### Removed
    \\
    \\### Fixed
    \\
    \\### Security
    \\
    \\## [0.0.1] - {date}
    \\
    \\### Added
    \\- Initial release
    \\
;

const env_template =
    \\# Environment Configuration
    \\# Copy this file to .env and update the values
    \\
    \\# Application
    \\NODE_ENV=development
    \\PORT=3000
    \\HOST=localhost
    \\
    \\# Database
    \\DATABASE_URL=postgresql://localhost:5432/myapp
    \\DB_HOST=localhost
    \\DB_PORT=5432
    \\DB_NAME=myapp
    \\DB_USER=myapp_user
    \\DB_PASSWORD=your_password_here
    \\
    \\# API Keys
    \\API_KEY=your_api_key_here
    \\SECRET_KEY=your_secret_key_here
    \\JWT_SECRET=your_jwt_secret_here
    \\
    \\# External Services
    \\REDIS_URL=redis://localhost:6379
    \\EMAIL_SERVICE_API_KEY=your_email_api_key
    \\STORAGE_BUCKET=your_storage_bucket
    \\
    \\# Logging
    \\LOG_LEVEL=info
    \\DEBUG=false
    \\
;

pub fn initFn(_options: []const cli.option) bool {
    var subcommand: ?[]const u8 = null;

    for (_options) |opt| {
        if (std.mem.eql(u8, opt.name, "subcommand")) {
            subcommand = opt.value;
            break;
        }
    }

    if (subcommand == null) {
        std.debug.print("Error: No subcommand provided\n", .{});
        std.debug.print("Usage: maki init <subcommand>\n", .{});
        std.debug.print("Available subcommands:\n", .{});
        std.debug.print("  readme    - Generate a README.md file\n", .{});
        std.debug.print("  license   - Generate a license file (coming soon)\n", .{});
        std.debug.print("  gitignore - Generate a .gitignore file (coming soon)\n", .{});
        std.debug.print("  changelog - Generate a CHANGELOG.md file\n", .{});
        std.debug.print("  env - Generate a .env.example file\n", .{});
        return false;
    }

    const subcmd = subcommand.?;

    if (std.mem.eql(u8, subcmd, "readme")) {
        return initReadmeFn(_options);
    } else if (std.mem.eql(u8, subcmd, "license")) {
        var license_type: ?[]const u8 = null;
        for (_options) |opt| {
            if (std.mem.eql(u8, opt.name, "type")) {
                license_type = opt.value;
                break;
            }
        }

        if (license_type == null and _options.len > 1) {
            for (_options) |opt| {
                if (std.mem.eql(u8, opt.name, "subcommand") and !std.mem.eql(u8, opt.value, "license")) {
                    license_type = opt.value;
                    break;
                }
            }
        }

        return initLicenseFn(license_type);
    } else if (std.mem.eql(u8, subcmd, "gitignore")) {
        return initGitignoreFn(_options);
    } else if (std.mem.eql(u8, subcmd, "changelog")) {
        return initChangelogFn(_options);
    } else if (std.mem.eql(u8, subcmd, "env")) {
        return initEnvFn(_options);
    } else {
        std.debug.print("Error: Unknown subcommand '{s}'\n", .{subcmd});
        std.debug.print("Available subcommands: readme, license, gitignore, changelog, env\n", .{});
        return false;
    }
}

pub fn subcommandFn(_: []const u8) bool {
    return true;
}

pub fn typeFn(_: []const u8) bool {
    return true;
}

pub fn initReadmeFn(_: []const cli.option) bool {
    const cwd_path = fs.cwd().realpathAlloc(std.heap.page_allocator, ".") catch {
        std.debug.print("Error: Could not get current directory\n", .{});
        return false;
    };
    defer std.heap.page_allocator.free(cwd_path);

    const project_name = fs.path.basename(cwd_path);

    if (fs.cwd().access("README.md", .{})) |_| {
        std.debug.print("README.md already exists. Overwrite? (y/N): ", .{});

        const stdin = std.io.getStdIn().reader();
        var buf: [10]u8 = undefined;
        if (stdin.readUntilDelimiterOrEof(&buf, '\n') catch null) |input| {
            if (input.len == 0 or (input[0] != 'y' and input[0] != 'Y')) {
                std.debug.print("Aborted.\n", .{});
                return true;
            }
        }
    } else |_| {}

    const file = fs.cwd().createFile("README.md", .{}) catch |err| {
        std.debug.print("Error creating README.md: {}\n", .{err});
        return false;
    };
    defer file.close();

    const writer = file.writer();

    var it = std.mem.tokenizeAny(u8, readme_template, "\n");
    while (it.next()) |line| {
        if (std.mem.indexOf(u8, line, "{project_name}")) |_| {
            var modified_line = std.ArrayList(u8).init(std.heap.page_allocator);
            defer modified_line.deinit();

            var start: usize = 0;
            while (std.mem.indexOf(u8, line[start..], "{project_name}")) |pos| {
                const abs_pos = start + pos;
                modified_line.appendSlice(line[start..abs_pos]) catch return false;
                modified_line.appendSlice(project_name) catch return false;
                start = abs_pos + "{project_name}".len;
            }
            modified_line.appendSlice(line[start..]) catch return false;

            writer.print("{s}\n", .{modified_line.items}) catch return false;
        } else if (std.mem.indexOf(u8, line, "{description}")) |_| {
            writer.print("A brief description of {s}\n", .{project_name}) catch return false;
        } else {
            writer.print("{s}\n", .{line}) catch return false;
        }
    }

    std.debug.print("Created README.md for project: {s}\n", .{project_name});
    std.debug.print("Don't forget to update the description and add specific details!\n", .{});

    return true;
}

pub fn initLicenseFn(license_type: ?[]const u8) bool {
    if (license_type == null) {
        std.debug.print("Error: No license type specified\n", .{});
        std.debug.print("Usage: maki init license <type>\n", .{});
        std.debug.print("Available license types:\n", .{});
        std.debug.print("  MIT       - MIT License\n", .{});
        std.debug.print("  Apache-2.0 - Apache License 2.0\n", .{});
        std.debug.print("  GPL-3.0   - GNU General Public License v3.0\n", .{});
        return false;
    }

    const license = license_type.?;

    var normalized_license: []const u8 = undefined;
    var filename: []const u8 = undefined;
    var template: []const u8 = undefined;

    if (std.ascii.eqlIgnoreCase(license, "MIT")) {
        normalized_license = "MIT";
        filename = "LICENSE";
        template = mit_license_template;
    } else if (std.ascii.eqlIgnoreCase(license, "Apache-2.0") or
               std.ascii.eqlIgnoreCase(license, "Apache2") or
               std.ascii.eqlIgnoreCase(license, "Apache")) {
        normalized_license = "Apache-2.0";
        filename = "LICENSE";
        template = apache2_license_template;
    } else if (std.ascii.eqlIgnoreCase(license, "GPL-3.0") or
               std.ascii.eqlIgnoreCase(license, "GPL3") or
               std.ascii.eqlIgnoreCase(license, "GPL")) {
        normalized_license = "GPL-3.0";
        filename = "LICENSE";
        template = gpl3_license_header;
    } else {
        std.debug.print("Error: Unknown license type '{s}'\n", .{license});
        std.debug.print("Available license types: MIT, Apache-2.0, GPL-3.0\n", .{});
        return false;
    }

    if (fs.cwd().access(filename, .{})) |_| {
        std.debug.print("{s} already exists. Overwrite? (y/N): ", .{filename});

        const stdin = std.io.getStdIn().reader();
        var buf: [10]u8 = undefined;
        if (stdin.readUntilDelimiterOrEof(&buf, '\n') catch null) |input| {
            if (input.len == 0 or (input[0] != 'y' and input[0] != 'Y')) {
                std.debug.print("Aborted.\n", .{});
                return true;
            }
        }
    } else |_| {}

    const timestamp = std.time.timestamp();
    const epoch_seconds = @as(u64, @intCast(timestamp));
    const year = 1970 + @divFloor(epoch_seconds, 31536000); // approx

    const author = "[Your Name]";

    const cwd_path = fs.cwd().realpathAlloc(std.heap.page_allocator, ".") catch {
        std.debug.print("Error: Could not get current directory\n", .{});
        return false;
    };
    defer std.heap.page_allocator.free(cwd_path);
    const project_name = fs.path.basename(cwd_path);

    const file = fs.cwd().createFile(filename, .{}) catch |err| {
        std.debug.print("Error creating {s}: {}\n", .{filename, err});
        return false;
    };
    defer file.close();

    const writer = file.writer();
    var it = std.mem.tokenizeAny(u8, template, "\n");
    while (it.next()) |line| {
        var modified_line = std.ArrayList(u8).init(std.heap.page_allocator);
        defer modified_line.deinit();

        var start: usize = 0;
        var modified = false;

        while (std.mem.indexOf(u8, line[start..], "{year}")) |pos| {
            const abs_pos = start + pos;
            modified_line.appendSlice(line[start..abs_pos]) catch return false;
            modified_line.writer().print("{d}", .{year}) catch return false;
            start = abs_pos + "{year}".len;
            modified = true;
        }

        start = if (modified) 0 else start;
        if (modified) {
            const temp = modified_line.toOwnedSlice() catch return false;
            defer std.heap.page_allocator.free(temp);
            modified_line = std.ArrayList(u8).init(std.heap.page_allocator);

            start = 0;
            while (std.mem.indexOf(u8, temp[start..], "{author}")) |pos| {
                const abs_pos = start + pos;
                modified_line.appendSlice(temp[start..abs_pos]) catch return false;
                modified_line.appendSlice(author) catch return false;
                start = abs_pos + "{author}".len;
            }
            modified_line.appendSlice(temp[start..]) catch return false;
        } else {
            while (std.mem.indexOf(u8, line[start..], "{author}")) |pos| {
                const abs_pos = start + pos;
                modified_line.appendSlice(line[start..abs_pos]) catch return false;
                modified_line.appendSlice(author) catch return false;
                start = abs_pos + "{author}".len;
                modified = true;
            }
        }

        if (std.mem.indexOf(u8, line, "{project_name}") != null) {
            const temp = if (modified) modified_line.toOwnedSlice() catch return false else line;
            defer if (modified) std.heap.page_allocator.free(temp);
            modified_line = std.ArrayList(u8).init(std.heap.page_allocator);

            start = 0;
            while (std.mem.indexOf(u8, temp[start..], "{project_name}")) |pos| {
                const abs_pos = start + pos;
                modified_line.appendSlice(temp[start..abs_pos]) catch return false;
                modified_line.appendSlice(project_name) catch return false;
                start = abs_pos + "{project_name}".len;
            }
            modified_line.appendSlice(temp[start..]) catch return false;
            modified = true;
        }

        if (modified) {
            writer.print("{s}\n", .{modified_line.items}) catch return false;
        } else {
            modified_line.appendSlice(line[start..]) catch return false;
            writer.print("{s}\n", .{modified_line.items}) catch return false;
        }
    }

    std.debug.print("Created {s} with {s} license\n", .{filename, normalized_license});
    std.debug.print("Remember to update the author name in the license file!\n", .{});

    return true;
}

pub fn initGitignoreFn(_options: []const cli.option) bool {
    var gitignore_type: ?[]const u8 = null;
    for (_options) |opt| {
        if (std.mem.eql(u8, opt.name, "type")) {
            gitignore_type = opt.value;
            break;
        }
    }

    if (gitignore_type == null) {
        std.debug.print("Error: No gitignore type specified\n", .{});
        std.debug.print("Usage: maki init gitignore <type>\n", .{});
        std.debug.print("Available types:\n", .{});
        std.debug.print("  node     - Node.js projects\n", .{});
        std.debug.print("  python   - Python projects\n", .{});
        std.debug.print("  zig      - Zig projects\n", .{});
        std.debug.print("  rust     - Rust projects\n", .{});
        std.debug.print("  go       - Go projects\n", .{});
        std.debug.print("  general  - General purpose\n", .{});
        return false;
    }

    const gitignore = gitignore_type.?;

    var template: []const u8 = undefined;
    var type_name: []const u8 = undefined;

    if (std.ascii.eqlIgnoreCase(gitignore, "node") or
        std.ascii.eqlIgnoreCase(gitignore, "nodejs") or
        std.ascii.eqlIgnoreCase(gitignore, "js")) {
        template = gitignore_node;
        type_name = "Node.js";
    } else if (std.ascii.eqlIgnoreCase(gitignore, "python") or
               std.ascii.eqlIgnoreCase(gitignore, "py")) {
        template = gitignore_python;
        type_name = "Python";
    } else if (std.ascii.eqlIgnoreCase(gitignore, "zig")) {
        template = gitignore_zig;
        type_name = "Zig";
    } else if (std.ascii.eqlIgnoreCase(gitignore, "rust") or
               std.ascii.eqlIgnoreCase(gitignore, "rs")) {
        template = gitignore_rust;
        type_name = "Rust";
    } else if (std.ascii.eqlIgnoreCase(gitignore, "go") or
               std.ascii.eqlIgnoreCase(gitignore, "golang")) {
        template = gitignore_go;
        type_name = "Go";
    } else if (std.ascii.eqlIgnoreCase(gitignore, "general")) {
        template = gitignore_general;
        type_name = "General";
    } else {
        std.debug.print("Error: Unknown gitignore type '{s}'\n", .{gitignore});
        std.debug.print("Available types: node, python, zig, rust, go, general\n", .{});
        return false;
    }

    if (fs.cwd().access(".gitignore", .{})) |_| {
        std.debug.print(".gitignore already exists. Overwrite? (y/N): ", .{});

        const stdin = std.io.getStdIn().reader();
        var buf: [10]u8 = undefined;
        if (stdin.readUntilDelimiterOrEof(&buf, '\n') catch null) |input| {
            if (input.len == 0 or (input[0] != 'y' and input[0] != 'Y')) {
                std.debug.print("Aborted.\n", .{});
                return true;
            }
        }
    } else |_| {}

    const file = fs.cwd().createFile(".gitignore", .{}) catch |err| {
        std.debug.print("Error creating .gitignore: {}\n", .{err});
        return false;
    };
    defer file.close();

    file.writeAll(template) catch |err| {
        std.debug.print("Error writing .gitignore: {}\n", .{err});
        return false;
    };

    std.debug.print("Created .gitignore for {s} projects\n", .{type_name});
    std.debug.print("You can customize it further based on your project needs!\n", .{});

    return true;
}

pub fn initChangelogFn(_: []const cli.option) bool {
    if (fs.cwd().access("CHANGELOG.md", .{})) |_| {
        std.debug.print("CHANGELOG.md already exists. Overwrite? (y/N): ", .{});

        const stdin = std.io.getStdIn().reader();
        var buf: [10]u8 = undefined;
        if (stdin.readUntilDelimiterOrEof(&buf, '\n') catch null) |input| {
            if (input.len == 0 or (input[0] != 'y' and input[0] != 'Y')) {
                std.debug.print("Aborted.\n", .{});
                return true;
            }
        }
    }else |_| {}

    const timestamp = std.time.timestamp();
    const epoch_seconds = @as(u64, @intCast(timestamp));
    const days_since_epoch = @divFloor(epoch_seconds, 86400);
    const year = 1970 + @divFloor(days_since_epoch, 365);
    const day_of_year = days_since_epoch % 365;
    const month = @min(12, 1 + @divFloor(day_of_year, 30));
    const day = @min(31, 1 + (day_of_year % 30));

    const file = fs.cwd().createFile("CHANGELOG.md", .{}) catch |err| {
        std.debug.print("Error creating CHANGELOG.md: {}", .{err});
        return false;
    };
    defer file.close();

    const writer = file.writer();
    var it = std.mem.tokenizeAny(u8, changelog_template, "\n");
    while (it.next()) |line| {
        if (std.mem.indexOf(u8, line, "{date}")) |_| {
            var modified_line = std.ArrayList(u8).init(std.heap.page_allocator);
            defer modified_line.deinit();

            var start: usize = 0;
            while (std.mem.indexOf(u8, line[start..], "{date}")) |pos| {
                const abs_pos = start + pos;
                modified_line.appendSlice(line[start..abs_pos]) catch return false;
                modified_line.writer().print("{d}-{d:0>2}-{d:0>2}", .{year, month, day}) catch return false;
                start = abs_pos + "{date}".len;
            }
            modified_line.appendSlice(line[start..]) catch return false;
            writer.print("{s}\n", .{modified_line.items}) catch return false;
        } else {
            writer.print("{s}\n", .{line}) catch return false;
        }
    }

    std.debug.print("Created CHANGELOG.md correctly.", .{});
    std.debug.print("Update with the changes you need.", .{});

    return true;
}

pub fn initEnvFn(_: []const cli.option) bool {
    if (fs.cwd().access(".env.example", .{})) |_| {
        std.debug.print(".env.example already exists. Overwrite? (y/N): ", .{});

        const stdin = std.io.getStdIn().reader();
        var buf: [10]u8 = undefined;
        if (stdin.readUntilDelimiterOrEof(&buf, '\n') catch null) |input| {
            if (input.len == 0 or (input[0] != 'y' and input [0] != 'Y')) {
                std.debug.print("Aborted.\n", .{});
                return true;
            }
        }
    }else |_| {}

    const file = fs.cwd().createFile(".env.example", .{}) catch |err| {
        std.debug.print("Error creating .env.example: {}\n", .{err});
        return false;
    };
    defer file.close();

    file.writeAll(env_template) catch |err| {
        std.debug.print("Error writing .env.example: {}\n", .{err});
        return false;
    };

    std.debug.print("Created .env.example with generic environment variables", .{});

    return true;
}